# Generated by Django 4.2.2 on 2023-07-17 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_rename_card_set_id_card_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardset',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(),
        ),
    ]
