# Generated by Django 4.2.2 on 2023-07-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_cardset_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='name',
            field=models.TextField(),
        ),
    ]
