# Generated by Django 4.2.2 on 2023-07-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_cardset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='cardset',
            name='last_name',
            field=models.CharField(default='LastName', max_length=100),
        ),
    ]
