# Generated by Django 4.2.2 on 2023-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0017_alter_cardset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="answer",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="card",
            name="question",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="cardset",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
