# Generated by Django 4.2.2 on 2023-07-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0015_alter_cardset_first_name_alter_cardset_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardset",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="cardset",
            name="last_name",
        ),
    ]
