# Generated by Django 4.2.2 on 2023-08-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0016_remove_cardset_first_name_remove_cardset_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardset",
            name="name",
            field=models.CharField(verbose_name=100),
        ),
    ]
