# Generated by Django 4.2.2 on 2023-08-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0018_alter_card_answer_alter_card_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="question",
            field=models.TextField(),
        ),
    ]
