# Generated by Django 4.2.2 on 2023-08-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0019_alter_card_answer_alter_card_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardset",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
